apiVersion: v1
kind: Pod
metadata:
  name: my-srver
spec:
  containers:
    - name: my-srver
      image: my-srver:1.0
      readinessProbe:
        httpGet:
          path: /healthz
          port: 80
        initialDelaySeconds: 30
        periodSeconds: 5
        successThreshold: 2
      livenessProbe:
        httpGet: #get请求
        path: /healthz
        port: 8080
        #请求的的head里会有 key为Custom-Header vlue为Awesome的值
        httpHeaders:
          - name: Custom-Header
            value: Awesome
        initialDelaySeconds: 3
        periodSeconds: 3
      lifecycle:
        preStop:
          exec:
            command: [ "/bin/sh","-c","./stop.sh"]
      resources:
        limits:
          memory: "200Mi"
        requests:
          memory: "100Mi"


